---
# Common variables for deployment
ansible_env_vars: "{{ lookup('file', playbook_dir + '/ansible_env.yml') | from_yaml }}"
# Project name - set this for your specific project
project_name: "{{ ansible_env_vars.PROJECT_NAME }}"

# Application settings
app_name: "{{ ansible_env_vars.DOKKU_APP_NAME }}"
db_name: "{{ ansible_env_vars.DOKKU_DB_NAME }}"
db_version: "14"
domain_name: "{{ ansible_env_vars.DOMAIN_NAME }}"
api_domain: "api.{{ ansible_env_vars.DOMAIN_NAME }}"

# S3 Storage
hetzner_s3_access_key: "{{ ansible_env_vars.HETZNER_S3_ACCESS_KEY }}"
hetzner_s3_secret_key: "{{ ansible_env_vars.HETZNER_S3_SECRET_KEY }}"
hetzner_s3_bucket_name: "{{ ansible_env_vars.HETZNER_S3_BUCKET_NAME }}"
s3_endpoint: "{{ ansible_env_vars.HETZNER_S3_ENDPOINT_URL }}"
s3_region: "{{ ansible_env_vars.HETZNER_S3_REGION_NAME }}"
# Backup bucket
s3_backup_bucket: "{{ ansible_env_vars.PROJECT_NAME }}-db-backups"

letsencrypt_email: "{{ ansible_env_vars.LETSENCRYPT_EMAIL }}"
